# Place this file in your projects root.
# Reember to replace <name> with your project name.
version: '3.7'

services:
  app:
    image: prlx/prlx-nginx-php-fpm:7.3-master
    volumes:
      - .:/src:rw,cached
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=<name>.local.parallax.dev
      - CERT_NAME=local.parallax.dev
      - SITE_NAME=<name>
      - SITE_BRANCH=master
      - ENVIRONMENT=local
      - DISABLE_OPCACHE="true"
      - DISABLE_CRON="true"
    working_dir: /src
  ide:
    image: theiaide/theia:next
    ports:
      - 3000:3000
    volumes:
      - .:/home/project:cached
volumes:
  app-sync:
    external: true
networks:
  default:
    external:
      name: parallax-proxy
