# Place this file in your projects root.
# Reember to replace <name> with your project name.
version: '3.7'

services:
  app:
    build:
      context: k8s/docker
      dockerfile: nginx-php
    volumes:
      - .:/src:rw,cached
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=<name>.local.parallax.dev
      - CERT_NAME=local.parallax.dev
      - SITE_NAME=<name>
      - SITE_BRANCH=master
      - ENVIRONMENT=local
      - DISABLE_OPCACHE="true"
      - DISABLE_CRON="true"
    working_dir: /src
  ide:
    image: theiaide/theia:next
    volumes:
    - .:/home/project:rw,delegated
    environment:
    - VIRTUAL_HOST=<name>.ide.local.parallax.dev
    - VIRTUAL_PORT=3000
    - CERT_NAME=local.parallax.dev
volumes:
  app-sync:
    external: true
networks:
  default:
    external:
      name: parallax-proxy
